# Lock down dist to ensure that builds run on a distribution that supports oraclejdk8
dist: trusty
language: ruby
rvm:
  - 2.1.3
jdk:
  - oraclejdk8
git:
  depth: 10
before_install:
  - gem update bundler
